---
title: "BFI_MI_1801_data"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
library(knitr)
library(pander)
panderOptions("table.split.table", Inf)
knitr::opts_chunk$set(echo = TRUE)
```

### Data

```{r, message = FALSE}
library(magrittr)
library(xlsx)
options(width = 180)
#> "무응답"은 NA가 되도록 코딩 처리하여야 함.
BFI <- "../data/BFI180411v2.xlsx" %>% 
  read.xlsx(sheetIndex = 1, 
            startRow = 3, 
            endRow = 182, 
            colIndex = c(4:5, 10:21), 
            header = FALSE, 
            stringsAsFactors = FALSE)
names(BFI) <- c("ID", "Name", "E1", "A1", "O1", "C1", "N1", "E2", "A2", "O2", "C2", "N2", "O3", "A3")
BFI %>% pander
MI <- "../data/MI180411v2.xlsx" %>% 
  read.xlsx(sheetIndex = 1, 
            startRow = 3, 
            endRow = 182, 
            colIndex = c(4, 8:63), 
            header = FALSE, 
            stringsAsFactors = FALSE)
names(MI) <- c("ID", paste0("Q", 1:56))
MI %>% str
MI %>% `[`(, 1:29) %>% pander
MI %>% `[`(, c(1,  30:57)) %>% pander
class_roll <- BFI %>% `[`(, 1:2)
class_roll
```

### Save Data

```{r, save.image}
save.image("./BFI_MI_1801v2.RData")
```

