---
title: "Quiz19 Submission Time"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(readr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
load("./red_and_black_180907_data.RData")
quiz19 <- read.xlsx("../data/etest19.xlsx", 
                        sheetIndex = 1, 
                        startRow = 3, 
                        endRow = 156, 
                        colIndex = 2:7, 
#                        colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
names(quiz19) <- c("name", "id", "dept", "score1", "score2", "time")
quiz19$group <- class_roll$group[match(quiz19$id, class_roll$id)]
quiz19$submit <- ifelse(is.na(quiz19$time), "미제출", "제출")
quiz19$hours_passed <- as.numeric(difftime(Sys.time(), quiz19$time, units = 'days'))
## 학교 정보시스템이 GMT로 표기되어 있어서 9시간의 타임갭을 감안하여야 함.
quiz19$days <- as.numeric(difftime("2018-12-03 09:00:00", quiz19$time, units = 'days'))
quiz19$hours <- as.numeric(difftime("2018-12-03 09:00:00", quiz19$time, units = 'hours'))
quiz19$bird <- factor(ifelse(quiz19$hours >= 10, "Early", "Late"), 
                      labels = c("마감일 오후2시 전 제출", "마감일 오후2시 이후 제출"))
str(quiz19)
```


### 제출/미제출

제출시간이 기록되지 않은 사람은 미제출.

```{r, echo = FALSE, results = "markup"}
pander(table(quiz19$group, quiz19$submit))
pander(chisq.test(table(quiz19$group, quiz19$submit)))
```

## 제출 시간의 분포

마감 시간으로부터 얼마나 일찍 제출하는지 일 단위와 시간 단위로 측정하여 살펴보았다. 

### 시간 단위 기초통계량

```{r, echo = FALSE}
# quiz19$hours
summary(quiz19$hours)
stem(quiz19$hours)
max(quiz19$hours, na.rm = TRUE)
```

### 일 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
pander(table(cut(quiz19$days, breaks = c(0:7), include.lowest = TRUE)), caption = "일 단위")
barplot(rev(table(cut(quiz19$days, breaks = c(0:7), include.lowest = TRUE))), 
        space = 0,
        names.arg = c("월", "화", "수", "목", "금", "토", "일"))
title(main = "일 단위 퀴즈 제출 횟수")
```

### 시간 단위 마감 시간으로부터 제출 시간의 분포

```{r, echo = FALSE}
breaks <- c(0:10, seq(24, 168, by = 24))
pander(table(cut(quiz19$hours, breaks = breaks, include.lowest = TRUE)), caption = "시간 단위")
```

### 시간 당 제출 건수의 분포

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
widths <- c(rep(24, 6), 14, rep(1, 10))
freqs <- table(cut(quiz19$hours, breaks = c(0:10, seq(24, 168, by = 24)), include.lowest = TRUE))
heights <- freqs / diff(breaks)
names_args <- c("월", "화", "수", "목", "금", "토", "일", rep("", 10))
barplot(height = rev(heights), width = widths, 
        space = 0,
        names.arg = names_args)
title(main = "시간당 퀴즈 제출 분포")
arrows(x0 = 148, y0 = 4, x1 = 157, y1 = 0.85, length = 0.15, code = 2, col = "red", lwd = 1.5)
text(x = 145, y = 4.5, labels = "오후 2시", srt = 15, col = "red")
```

### 급히 제출한 사람과 일찍 낸 사람 비교

마감 당일 오후 2시 이후에 제출한 사람과 그 이전에 제출한 사람들의 특성 비교

#### 랜덤화 효과

```{r, echo = FALSE}
pander(table(quiz19$group, quiz19$bird))
```

#### 기초통계 비교

```{r, echo = FALSE}
pander(tapply(quiz19$score1, quiz19$bird, summary))
```

#### Box Plot

```{r, echo = FALSE}
par(family = "HCR Dotum LVT")
plot(score1 ~ bird, data = quiz19, 
     main = "마감일 오후 2시 전부터 제출한 사람과 그 이후에 낸 사람", 
     xlab = "제출 시점", ylab = "퀴즈 점수")
```

#### t test

```{r, echo = FALSE}
pander(t.test(score1 ~ bird, data = quiz19))
```

## Save

```{r, echo = FALSE}
saveRDS(quiz19, file = "quiz19.RDs")
```