---
title: "생활 속의 통계학 최종"
author: "금융정보통계학과 이기원교수"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(width=180)
rm(list=ls())
```

```{r, presets, , message = FALSE, echo = FALSE}
options(digits = 3)
library(xlsx)
library(knitr)
library(pander)
panderOptions("table.split.table", Inf)
```

<!--### Facebook Data-->

```{r facebook, eval = FALSE, message = FALSE, echo = FALSE}
fb <- read.xlsx(file="../data/class_roll_Facebook_v2.xlsx", 
                sheetIndex = 1, 
                rowIndex = 3:182, 
                colIndex = c(4:5, 10:23), 
                header = FALSE, 
                colClasses = c(rep("character", 2), rep("numeric", 13), "character"))
v.names.fb <- c("ID", 
                "Name", 
                "Strack",
                "Rosling1", 
                "Rosling2", 
                "Boushnak",
                "Rosling3",
                "GDP",
                "Ariely",
                "Wilkinson", 
                "Hanauer", 
                "Zimbardo", 
                "Little", 
                "Ramachandran",
                "Total",
                "Group")
names(fb) <- v.names.fb
# is.na(fb[, -(1:2)])
# fb.score <- ifelse(is.na(fb[, -(1:2)]), 0, 1)
# n.fb <- ncol(fb.score)
# fb$sum <- rowSums(fb.score)
fb$Score <- fb$Total * 30 / 12
kable(fb[c("ID", "Name", "Score")], 
      align = c("c", "c", "r"))
fb_score <- fb$Score
```

<!--### Online Attendance-->

```{r Assignment, eval = TRUE, message = FALSE, echo = FALSE, results = 'hide'}
assignment <- read.xlsx(file = "../data/assignment_v5.xlsx", 
                        sheetIndex = 1, 
                        rowIndex = 2:181, 
                        colIndex = c(3:4, 6:7), 
                        header = TRUE, 
                        colClasses = c(rep("character", 2), 
                                       rep("numeric", 2)),
                        stringsAsFactors = FALSE)
v.names.assignment <- c("ID", "Name", "Term1", "Term2")
names(assignment) <- v.names.assignment
# online[c("Salk", "Poll")]
# kable(assignment)
# assignment[, 3][is.na(assignment[, 3])] <- 0
# assignment[, 4][is.na(assignment[, 4])] <- 0
assignment[, 3:4] <- assignment[, 3:4] / 5
# assignment[, 3:4] <- assignment[, 3:4] * 12 / 100 + 8
assignment[, 3][is.na(assignment[, 3])] <- 0
assignment[, 4][is.na(assignment[, 4])] <- 0
kable(assignment)
```

<!--### Team Projects-->

```{r Team Projects, eval = FALSE, message = FALSE, echo = FALSE}
project <- read.xlsx(file="../data/class_roll_project.xlsx", sheetIndex= 1, rowIndex = 2:70, colIndex = c(4:5, 10:30), colClasses = c(rep("character", 3), rep("numeric", 20)))
# pander(project)
team.score <- round(colMeans(project[, -c(1:3, 21:23)], na.rm = TRUE), digits = 2)
pander(team.score)
# project$Score <- project$"계"*10
project$Score <- team.score[match(project$"조이름", names(team.score))]
kable(project[c(1:3, 24)])
```

<!--### Integration-->

```{r Integration, eval = FALSE, message = FALSE, echo = FALSE}
fb.score <- fb[, "Score"]
online.score <- online[, "Score"]
project.score <- project[, "Score"]
scores <- data.frame(fb[c("ID", "Name")], FB = fb.score, Online = online.score, Project = project.score)
kable(scores)
```

<!--### Total Scores-->

```{r, Total Scores, message = FALSE, echo = FALSE}
total <- read.xlsx(file = "../data/scoreList_v8.xlsx", 
                   sheetIndex = 1, 
                   rowIndex = 3:182, 
                   colIndex = 2:8, 
                   colClasses = c(rep("character", 2), rep("numeric", 5)), 
                   header = TRUE,
                   stringsAsFactors = FALSE)
total <- total[c(2, 1, 5, 7, 4, 6, 3)]
v.names.total <- c("ID", "Name", "Offline", "Online", "Assignment", "Facebook", "Total")
names(total) <- v.names.total
total <- merge(total, assignment)
total$Total <- total$Total - total$Assignment + total$Term1 + total$Term2
```

## FA list
 
```{r, FA_list, eval = TRUE, message = FALSE, echo = FALSE}
FA_id <- c("20175101", "20175140")
n_FA <- length(FA_id)
FA <- which(total$ID %in% FA_id)
kable(total[FA, c(1:4, 8:9, 6:7)])
```

## Ranks and Grades

```{r, Scores and Ranks, message = FALSE, echo = FALSE}
# total <- total[-FA, ]
# total$Facebook[total$Name == "조유정"] <- 30
# total$Total[total$Name == "조유정"] <- total$Total[total$Name == "조유정"] + 2.5
# kable(total)
# total.order <- total[match(fb$ID, total$ID), ]
# kable(total.order)
# N <- nrow(total.order)
N <- nrow(total)
# total.order$Ranks <- N + 1 - rank(total.order$Total)
# total.2 <- total
# total.2$Assignment < total$Assignment/2
# total.2$Term_Project <- total$Term_Project*3/2
total$Ranks <- N + 1 - rank(total$Total)
#total.order$Grades <- ifelse(total.order$Ranks <= floor(N*0.3), "A+", ifelse(total.order$Ranks <= floor(N*0.6), "B+", "C+"))
#total.order$Grades <- ifelse(total.order$Ranks <= floor(N*0.3), "A+", ifelse(total.order$Ranks <= floor(N*0.6), "B+", ifelse(total.order$Project <= 0, "F", ifelse(total.order$Name == "ANGIRMAA GANBAT", "B+", "C+"))))
total$Grades <- ifelse(total$Ranks <= floor((N - n_FA) * 0.3), 
                       "A+", 
                       ifelse(total$Ranks <= floor((N - n_FA) * 0.6), 
                              "B+", 
                              ifelse(total$Total > 0, 
                              "C+", "F")))
# total[total$Name %in% c("김범준"), "Grades"] <- "B+"
total[total$ID %in% FA_id, "Grades"] <- "FA"
kable(total[, c(1:4, 8:9, 6:7, 10:11)])
```

```{r, eval = TRUE, echo = TRUE}
#> Facebook 만점자
kable(total[total$Facebook == 30, c(1:4, 8:9, 6:7, 10:11)])
nrow(total[total$Facebook == 30, c(1:4, 8:9, 6:7, 10:11)])
#> 출석, 페이스북 만점자
kable(total[total$Offline == 20 & total$Online == 10 & total$Facebook == 30, 
            c(1:4, 8:9, 6:7, 10:11)])
nrow(total[total$Offline == 20 & total$Online == 10 & total$Facebook == 30, 
            c(1:4, 8:9, 6:7, 10:11)])
#> A 학점자
kable(total[total$Grades == "A+", c(1:4, 8:9, 6:7, 10:11)])
nrow(total[total$Grades == "A+", c(1:4, 8:9, 6:7, 10:11)])
total1226 <- readRDS("total1226.RDS")
#> `total` 과 `total1226` 의 인적사항(ID) 일치 여부
all(total$ID == total1226$ID)
#> 상승된 점수 비교 요약
summary(total$Total - total1226$Total)
#> 줄기-잎 그림 비교
stem(total1226$Total)
stem(total$Total)
stem(total$Term2)
#> 기말과제 점수 요약
summary(total$Term2)
#> 1900자 이상 200자 미만 기술한 사람 수효
sum(total$Term2 >= 19)
#> A 받은 사람 수효
sum(total1226$Grades == "A+")
#> A에서 B로 내려간 사람 내역
A2B <- which(total1226$Grades == "A+" & total$Grades == "B+")
kable(data.frame(total1226[A2B, c("ID", "Name", "Total", "Ranks", "Grades")], total[A2B, c("Total", "Ranks", "Grades")]))
length(A2B)
#> B에서 C로 내려간 사람 내역
B2C <- which(total1226$Grades == "B+" & total$Grades == "C+")
kable(data.frame(total1226[B2C, c("ID", "Name", "Total", "Ranks", "Grades")], total[B2C, c("Total", "Ranks", "Grades")]))
length(B2C)
#> B에서 A로 올라간 사람 내역
B2A <- which(total1226$Grades == "B+" & total$Grades == "A+")
kable(data.frame(total1226[B2A, c("ID", "Name", "Total", "Ranks", "Grades")], total[B2A, c("Total", "Ranks", "Grades")]))
length(B2A)
#> C에서 B로 올라간 사람 내역
C2B <- which(total1226$Grades == "C+" & total$Grades == "B+")
kable(data.frame(total1226[C2B, c("ID", "Name", "Total", "Ranks", "Grades")], total[C2B, c("Total", "Ranks", "Grades")]))
length(C2B)
# total.2 <- total
# total.2$Assignment <- total$Assignment/2
# total.2$Term_Project <- total$Term_Project*3/2
# total.2$Total <- apply(total.2[, 3:7], 1, sum)
# total.2$Ranks <- N + 1 - rank(total.2$Total)
# total.2$Grades <- ifelse(total.2$Ranks <= floor(N*0.3), "A+", ifelse(total.2$Ranks <= floor(N*0.6), "B+", "C+"))
# kable(total.2)
```

<!--
<P style = "page-break-before:always">
-->

```{r, individual scores, eval = TRUE, echo = FALSE}
total <- total[, c(1:4, 8:9, 6:7, 10:11)]
v.names.kr <- c("학번", "이름", "교실(20)", "온라인(10)", "중간과제(20)", "기말과제(20)", "페이스북(30)", "총점(100)", "순위(177명중)", "학점")
total.kr <- total
names(total.kr) <- v.names.kr
my.grade <- function(name){
  kable(total.kr[total$Name %in% name, -1], row.names = FALSE)
}
# my.grade(c("강보경", "이소연", "최용훈", "강정우", "박진욱", "박지민", "전강수", "권지연", "양아영", "윤동준", "이한솔", "장대혁", "장민호"))
# my.grade(c("김현진", "이창호", "김혜지", "김관호"))
# my.grade("안나정")
# my.grade("이재기")
# my.grade("정연주")
# my.grade("강예은")
# my.grade("조유정")
# my.grade("이한솔")
# my.grade("최성훈")
# my.grade("김성호")
# my.grade("명기웅")
#> 201702
# my.grade("이동현")
# my.grade("김찬희")
# my.grade("김도헌")
# my.grade("이승기")
# my.grade("이학준")
# my.grade("김민지")
# my.grade("김민희")
# my.grade("김효은")
# my.grade("한원형")
# my.grade("박용화")
# my.grade("임지원")
# my.grade("최경진")
# my.grade("이인용")
# my.grade("김민희")
# my.grade("이호진")
# my.grade("고동진")
# my.grade("김효은")
# my.grade("이학준")
# my.grade("한원형")
# my.grade("이승기")
# my.grade("김도헌")
# my.grade("김찬희")
# my.grade("이동현")
# my.grade("김범준")
# my.grade("김하은")
# my.grade("함형권")
# my.grade("김지환")
# my.grade("김태환")
# my.grade("이호진")
# my.grade("김현주")
# my.grade("조정윤")
# my.grade("조현종")
# my.grade("최홍석")
# my.grade("강정수")
# my.grade("양솔하")
# my.grade("안예은")
# my.grade("조단비")
# my.grade("최진우")
# my.grade("고동진")
# my.grade("김진희")
# my.grade("조현종")
# my.grade("김민철")
# my.grade("이승비")
# my.grade("이서영")
# my.grade("한은비")
# my.grade("최현식")
my.grade("채영수")
# my.grade("김민주")
# my.grade("권하은")
my.grade("천가람")
my.grade("김지환")
# my.grade("임유정")
my.grade("이명규")
```

<!--### Save Data

```{r Save Data, echo = FALSE}
save.image(file = "../R/final_Records1229.RData")
```

-->
               