---
title: "Food Habits Plan 181015"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

<!--
### Data 
-->

```{r, data, echo = FALSE, results = 'hide'}
food <- read.xlsx("../data/food_plan_181015_recoding.xlsx", 
                  sheetIndex = 1, 
                  startRow = 2, endRow = 155, 
                  colIndex = c(3:7, 9:30), 
                  colClasses = c(rep("character", 6), rep("numeric", 20), "character"),
                  stringsAsFactors = FALSE)
str(food)
names(food) <- c("dept", "id", "name", "year", "e.mail", "cell.no", paste("Q", 1:20, sep = ""), "group")
food$dept <- factor(food$dept)
food$year <- factor(food$year)
food$group <- factor(food$group, levels = c("Red", "Black"))
#> 출석은 하였으나 한 항목 이상 응답하지 않은 학생의 항목 점수를 최빈값으로 대체
all_na <- which(apply(food[paste("Q", 1:20, sep = "")], 1, function(x) all(is.na(x))))
any_na <- which(apply(food[paste("Q", 1:20, sep = "")], 1, function(x) any(is.na(x))))
na_ind <- setdiff(any_na, all_na)
q_na <- apply(food[na_ind, paste("Q", 1:20, sep = "")], 1, function(x) which(is.na(x)))
paste0("Q", q_na)
sapply(food[paste0("Q", q_na)], table)
food[60, "Q17"] <- 3
food[67, "Q10"] <- 2
food[98, "Q17"] <- 3
food[107, "Q13"] <- 3
#> 대체한 값으로 점수 계산
food$score <- apply(food[paste("Q", 1:20, sep = "")], 1, sum)
food$grade <- ifelse(food$score <= 59, "식생활을 고치세요", ifelse(food$score <= 79, "식생활이 보통입니다", ifelse(food$score <= 100, "식생활이 대체로 좋아요", NA)))
food$grade <- factor(food$grade, levels = c("식생활을 고치세요", "식생활이 보통입니다", "식생활이 대체로 좋아요"), ordered = TRUE)
str(food)
```

### Descriptive Statistics

#### Grades

```{r, grades, echo = FALSE}
# pander(food[c("id", "name", "score", "grade")])
pander(food[c("id", "score", "grade")])
```

#### Cross Tables

```{r, cross table, echo = FALSE}
food.tbl <- table(food$group, food$grade, exclude = NULL)
food.tbl.a <- addmargins(food.tbl)
colnames(food.tbl.a)[4:5] <- c("결석", "계")
rownames(food.tbl.a)[3] <- "계"
pander(food.tbl.a)
```

#### Percentages

```{r, echo = FALSE}
food.p <- food.tbl.a[3, -(4:5)] / sum(food.tbl.a[3, -(4:5)]) * 100
food.p <- c(food.p, sum(food.p))
names(food.p)[4] <- "계"
pander(format(food.p, digits = 2, nsmall = 1))
```

#### Summary Statistics

```{r, summary, echo = FALSE}
pander(tapply(food$score, food$group, summary))
```

#### Standard Deviation

```{r, SD, echo = FALSE}
pander(tapply(food$score, food$group, sd, na.rm = TRUE), caption = "Standard Deviation")
```

#### t test (Welch's)

```{r, t test, echo = FALSE}
pander(t.test(score ~ group, data = food))
```

### Plots

#### Stem and Leaf

```{r, stem and leaf, echo = FALSE}
tapply(food$score, food$group, stem)
```

#### Box plot

```{r, Box plot, echo = FALSE, fig.width = 7, fig.height = 7}
plot(score~group, data = food)
```

#### QQplot

```{r, qqplot, echo = FALSE, fig.width = 7, fig.height = 7}
Black <- food$group == "Black"
Red <- food$group == "Red"
qqplot(food$score[Black], food$score[Red], xlab = "Black", ylab = "Red")
```

<!--
### save
-->

```{r, echo = FALSE}
saveRDS(food, "./food_after1802.rds")
```