---
title: "Quiz 170830"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
options(width=180)
```

```{r, data}
quiz0830 <- read.xlsx("../data/quiz170830.xlsx", 
                      1, 
                      startRow = 2, 
                      endRow = 182, 
                      colIndex = c(3:7, 9:14), 
                      colClasses = c(rep("character", 11)), 
                      stringsAsFactors = FALSE)
pander(quiz0830)
names(quiz0830) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0830$dept <- factor(quiz0830$dept)
quiz0830$year <- factor(quiz0830$year)
quiz0830$group <- factor(quiz0830$group, 
                         levels = c("Red", "Black"))
quiz0830$Q1 <- factor(quiz0830$Q1, 
                      levels = 1:5, 
                      labels = c("공자", "맹자", "관자", "노자", "장자"))
quiz0830$Q2 <- factor(quiz0830$Q2, 
                      levels = 1:5, 
                      labels = c("절대 중요 않음", "거의 중요 않음", "보통", "상당히 중요", "절대 중요"))
quiz0830$Q3 <- factor(quiz0830$Q3, 
                      levels = 1:4, 
                      labels = c("2012", "2016", "2020", "2030"))
quiz0830$Q4 <- factor(quiz0830$Q4, 
                      levels = 1:3, 
                      labels = c("찬성 입장", "반대 입장", "모름/무응답"))
quiz0830$Q4.2 <- quiz0830$Q4
levels(quiz0830$Q4.2)
levels(quiz0830$Q4.2) <- c("찬성", "반대", "모름/무응답")
# pander(quiz0830)
```

```{r, randomization}
pander(summary(quiz0830))
```

```{r, id}
pander(table(quiz0830$group, quiz0830$Q1, 
             exclude = NULL), 
       caption = "춘추시대 국가통계관리")
pander(addmargins(table(quiz0830$group, quiz0830$Q1, 
                        exclude = NULL), 
                  margin = 1), 
       caption = "춘추시대 국가통계관리")
pander(round(prop.table(addmargins(table(quiz0830$group, quiz0830$Q1, 
                                         exclude = NULL), 
                                   margin = 1), 
                        margin = 1)[4, ] * 100, 
             digits = 1), 
       caption = "춘추시대 국가통계관리")
pander(table(quiz0830$group, quiz0830$Q2, 
             exclude = NULL), 
       caption="통계의 역할")
pander(addmargins(table(quiz0830$group, quiz0830$Q2, 
                        exclude = NULL), 
                  margin = 1), 
       caption = "통계의 역할")
pander(round(prop.table(addmargins(table(quiz0830$group, quiz0830$Q2, 
                                         exclude = NULL), 
                                   margin = 1), 
                        margin = 1)[4, ] * 100, 
             digits = 1), 
       caption = "통계의 역할")
pander(table(quiz0830$group, quiz0830$Q3, 
             exclude = NULL), 
       caption = "생산가능인구 감소")
pander(addmargins(table(quiz0830$group, quiz0830$Q3, 
                        exclude = NULL), 
                  margin = 1), 
       caption = "생산가능인구 감소")
pander(round(prop.table(addmargins(table(quiz0830$group, quiz0830$Q3, 
                                         exclude = NULL), 
                                   margin = 1), 
                        margin = 1)[4, ] * 100, 
             digits = 1), 
       caption = "생산가능인구 감소")
pander(table(quiz0830$group, quiz0830$Q4, 
             exclude = NULL), 
       caption = "테러방지법")
pander(table(quiz0830$group, quiz0830$Q4.2, 
             exclude = NULL), 
       caption = "테러방지법")
thaad.tbl <- table(quiz0830$group, quiz0830$Q4)
thaad.tbl.2 <- table(quiz0830$group, quiz0830$Q4.2)
pander(round(prop.table(thaad.tbl, 
                        margin = 1) * 100, 
             digits = 1), 
       caption = "테러방지법(단위, %)")
pander(round(prop.table(thaad.tbl.2, 
                        margin = 1) * 100, 
             digits = 1), 
       caption = "테러방지법(단위, %)")
```

```{r, save}
#save.image("../R/quiz0830.RData")
```