---
title: "Wason Selection"
author: "coop711"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
library(xlsx)
library(pander)
library(knitr)
panderOptions('table.split.table', Inf)
panderOptions('table.alignment.rownames', 'left')
panderOptions('table.alignment.default', 'right')
options(width = 180)
```

```{r, data, echo = FALSE, results = 'hide'}
quiz0509 <- read.xlsx("../data/quiz0509.xlsx", 1, startRow = 2, endRow = 66, colIndex = c(3:7, 9:14), colClasses = c(rep("character", 11)), stringsAsFactors = FALSE)
str(quiz0509)
names(quiz0509) <- c("dept", "id", "name", "year", "e.mail", "cell.no", "Q1", "Q2", "Q3", "Q4", "group")
quiz0509$dept <- factor(quiz0509$dept)
quiz0509$year <- factor(quiz0509$year)
quiz0509$group <- factor(quiz0509$group, levels = c("Red", "Black"))
quiz0509$Q1 <- factor(quiz0509$Q1, levels = c("가", "나", "다", "라"), labels = c("랜덤화", "가짜약 대조군", "이중눈가림", "층화"))
quiz0509$Q2 <- factor(quiz0509$Q2, levels = c("가", "나", "다", "라"), labels = c("28 vs 46", "28 vs 71", "28 vs 25", "25 vs 54"))
quiz0509[c("Q3", "Q4", "group")]
quiz0509$Q3.2 <- quiz0509$Q3
Black <- quiz0509$group == "Black"
Red <- quiz0509$group == "Red"
quiz0509$Q3.2[Black] <- ifelse(quiz0509$Q3[Black] == "Beer,17", "Right", "Wrong")
quiz0509$Q3.2[Red] <- ifelse(quiz0509$Q3[Red] == "A,3", "Right", "Wrong")
# quiz0509$Q3.2[quiz0509$group == "Black" & quiz0509$Q3 == "Beer,17"] <- "Right"
# quiz0509$Q3.2[quiz0509$group == "Black" & quiz0509$Q3 != "Beer,17"] <- "Wrong"
# quiz0509$Q3.2[quiz0509$group == "Red" & quiz0509$Q3 == "A,3"] <- "Right"
# quiz0509$Q3.2[quiz0509$group == "Red" & quiz0509$Q3 != "A,3"] <- "Wrong"
quiz0509$Q3.2
quiz0509$Q4.2 <- quiz0509$Q4
quiz0509$Q4.2[Black] <- ifelse(quiz0509$Q4[Black] == "A,3", "Right", "Wrong")
quiz0509$Q4.2[Red] <- ifelse(quiz0509$Q4[Red] == "Beer,17", "Right", "Wrong")
# quiz0509$Q4.2[quiz0509$group == "Black" & quiz0509$Q4 == "A,3"] <- "Right"
# quiz0509$Q4.2[quiz0509$group == "Black" & quiz0509$Q4 != "A,3"] <- "Wrong"
# quiz0509$Q4.2[quiz0509$group == "Red" & quiz0509$Q4 == "Beer,17"] <- "Right"
# quiz0509$Q4.2[quiz0509$group == "Red" & quiz0509$Q4 != "Beer,17"] <- "Wrong"
quiz0509[c("Q3", "Q3.2", "Q4", "Q4.2", "group")]
str(quiz0509)
```

```{r, randomization, echo = FALSE, results = 'hide'}
pander(summary(quiz0509))
```

<!--
### Salk Vaccine Field Trial

#### Randomized Placebo Control Approach의 특징 

##### Randomization

```{r, randomized placebo control approach, echo = FALSE}
tbl.q1.a <- addmargins(table(quiz0509$group, quiz0509$Q1, useNA = "ifany"), margin = 1) 
pander(tbl.q1.a, caption = "랜덤화")
```

##### Randomization (%)

```{r, randomized placebo control approach in percentage, echo = FALSE}
percentage.tbl.q1.a <- addmargins(round(prop.table(tbl.q1.a[, -5], margin = 1)*100, digits = 1))[3, ]
names(percentage.tbl.q1.a)[5] <- "계"
pander(percentage.tbl.q1.a, "랜덤화")
```

#### Clear Evidence of Vaccine Effects

##### Treatment vs Control

```{r, Treatment vs Control, echo = FALSE}
tbl.q2.a <- addmargins(table(quiz0509$group, quiz0509$Q2, useNA = "ifany"), margin = 1)
pander(tbl.q2.a)
```

##### Treatment vs Control (%)

```{r, opposite in percentage, echo = FALSE}
percentage.tbl.q2.a <- addmargins(round(prop.table(tbl.q2.a[, -5], margin = 1)*100, digits = 1))[3, ]
names(percentage.tbl.q2.a)[5] <- "계"
pander(percentage.tbl.q2.a, caption = "쏘오크 예방주사의 효과")
```

### Wason Selection


#### 추상적 표현과 구체적 표현?

같은 내용의 문제를 추상적으로 물어볼 때와 구체적으로 사례를 들어서 물어볼 때의 정답률에 큰 차이가 있음에 유의. Red 집단에게는 추상적 질문을 먼저 던지고, 구체적 사례를 든 질문을 나중에 던졌으며 Black 집단에게는 구체적 사례를 든 질문을 먼저 던지고, 추상적 질문을 나중에 던졌다. 동일한 질문에 대해서 순서에 따른 차이는 거의 없지만 추상적이냐 구체적이냐에 따른 차이는 매우 높게 관찰된다. 추상적인 질문에 쩔쩔매는 게 정상이다.

##### Red에 추상적 문제 먼저 질문 

```{r, Wason Selection 1 in Red, echo = FALSE}
tbl.q3.a <- addmargins(table(quiz0509$group, quiz0509$Q3.2, useNA = "ifany"), margin = 1)
rownames(tbl.q3.a) <- c("Red(추상적 질문 먼저)", "Black(구체적 질문 먼저)", "계") 
# tbl.q3.a <- addmargins(tbl.q3, margin = 1)
kable(tbl.q3.a, caption = "Wason Selection 1 in red")
```

##### % 비교  

```{r, Wason Selection 1 in Red in percentage, echo = FALSE}
percentage.tbl.q3.a <- addmargins(round(prop.table(tbl.q3.a[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(percentage.tbl.q3.a) <- c("정답", "오답", "계")
kable(percentage.tbl.q3.a, caption = "Wason Selection 1 in red")
```

##### Black에 추상적 문제 먼저 질문 

```{r, Wason Selection 1 in Black, echo = FALSE}
tbl.q4.a <- addmargins(table(quiz0509$group, quiz0509$Q4.2, useNA = "ifany"), margin = 1)
rownames(tbl.q4.a) <- c("Red(구체적 질문 먼저)", "Black(추상적 질문 먼저)", "계")
kable(tbl.q4.a, caption = "Wason Selection 1 in Black")
```

##### % 비교.  

```{r, Wason Selection 1 in Black in percentage, echo = FALSE}
percentage.tbl.q4.a <- addmargins(round(prop.table(tbl.q4.a[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(percentage.tbl.q4.a) <- c("정답", "오답", "계")
kable(percentage.tbl.q4.a, caption = "Wason Selection 1 in Black")
```

#### 합산

##### 집계표
-->

```{r, Wason Selection, echo = FALSE}
wason_1 <- tbl.q3.a[1, ] + tbl.q4.a[2, ]
wason_2 <- tbl.q3.a[2, ] + tbl.q4.a[1, ]
wason.tbl <- as.table(rbind(wason_1, wason_2))
rownames(wason.tbl) <- c("Wason 1(추상적 질문)", "Wason 2(구체적 질문)")
colnames(wason.tbl) <- c("정답", "오답", "결석")
kable(wason.tbl, caption = "Wason Selection")
```

##### % 비교

```{r, Wason Selection in percentage, echo = FALSE}
wason.tbl.p.a <- addmargins(round(prop.table(wason.tbl[, -3], margin = 1)*100, digits = 1))[1:2, ]
colnames(wason.tbl.p.a) <- c("정답", "오답", "계")
kable(wason.tbl.p.a, caption = "Wason Selection")
```



```{r, save, echo = FALSE}
#save.image("../R/quiz0509.rda")
```