---
# title: "Red and Black 180907"
# author: "coop711"
# date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("pander", repos = "https://cran.rstudio.com")
# install.packages("xlsx", repos = "https://cran.rstudio.com")
# install.packages("readr", repos = "https://cran/rstudio.com")
library(xlsx)
library(pander)
library(knitr)
library(readr)
panderOptions('table.split.table', Inf)
options(width = 180)
```

<!--
### Data
-->

```{r, data, echo = FALSE, results = "hide"}
load("./red_and_black_180904_data.RData")
class_roll0904 <- class_roll
str(class_roll0904)
class_roll <- read.xlsx("../data/class_roll0907.xlsx", 
                        sheetIndex = 1, 
                        startRow = 2, 
                        endRow = 158, 
                        colIndex = c(3:7, 9), 
                        colClasses = rep("character", 6), 
                        encoding = "UTF-8",
                        stringsAsFactors = FALSE)
str(class_roll)
str(class_roll0904)
names(class_roll) <- c("dept", "id", "name", "year", "e.mail", "cell.no")
class_roll0904$mark <- "0904"
names(class_roll0904)[8] <- "mark1"
class_roll$mark2 <- "0907"
class_roll.merged <- merge(class_roll, class_roll0904, 
                                by = "id", 
                                all = TRUE)

```


### 9월 4일자 출석부와 9월 7일자 출석부 통합 결과

`group`, `mark1`이 NA인 사람은 새로 들어온 사람이고, `mark2`가 NA인 사람은 나간 사람임.

```{r, echo = FALSE, results = "markup"}
nrow(class_roll.merged)
pander(class_roll.merged[, c("group", "mark1", "mark2")])
```

### 9월 4일자 출석부에만 나오는 사람들의 분포

```{r, echo = FALSE}
class_roll.out <- class_roll.merged[is.na(class_roll.merged$mark2), ]
pander(class_roll.out[, c("group", "mark1", "mark2")])
pander(table(class_roll.out$group))
# pander(class_roll.merged[is.na(class_roll.merged$mark2), 
#                          c("group", "mark1", "mark2")])
# pander(table(class_roll.merged[is.na(class_roll.merged$mark2), ]$group))
```

```{r, echo = FALSE, results = "hide"}
id0904 <- class_roll0904$id
id0907 <- class_roll$id
stay0907 <- intersect(id0904, id0907)
length(stay0907)
new_id <- setdiff(id0907, id0904)
class_roll.stay <- subset(class_roll0904, id %in% stay0907)
class_roll.new <- subset(class_roll, id %in% new_id)
str(class_roll.stay)
str(class_roll.out)
str(class_roll.new)
str(class_roll)
```

### 새로 들어온 사람에게만 랜덤화 적용

```{r, sub randomization, echo = FALSE, eval = TRUE}
set.seed(16)
N <- nrow(class_roll.new) 
d <- unname(diff(table(class_roll.out$group)))
N_red <- (N - d) / 2
id_red <- sample(1:N, size = 6)
# id_red <- sample(1:N, size = 7)
id_black <- setdiff(1:N, id_red)
class_roll.new$group <- ifelse(1:N %in% id_red, "Red", "Black")
# class_roll.new$group <- sample(1:N) %% 2 + 1
class_roll.new$group <- factor(class_roll.new$group, 
                           levels = c("Red", "Black"))
# class_roll.new$group <- factor(class_roll.new$group, 
#                            levels = c("Red", "Black"))
class_roll.new <- class_roll.new[, c(1:6, 8, 7)]
names(class_roll.stay)[8] <- "mark"
names(class_roll.new)[8] <- "mark"
red.id <- which(class_roll.new$group == "Red")
black.id <- which(class_roll.new$group == "Black")
class_roll <- rbind(class_roll.stay, class_roll.new)
```

<!--
### Randomization for All
-->

```{r, randomization, echo = FALSE, eval = FALSE}
set.seed(11)
N <- nrow(class_roll) 
class_roll$group <- sample(1:N) %% 2 + 1
class_roll$group <- factor(class_roll$group, 
                           labels = c("Red", "Black"))
red.id <- which(class_roll$group == "Red")
black.id <- which(class_roll$group == "Black")
```

### 학번

```{r, id, echo = FALSE}
ID.18 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2018, 
                       "younger.18", "older.18"), 
                levels = c("younger.18", "older.18"))
pander(table("18학번 기준" = ID.18, "그룹" = class_roll$group))
ID.17 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2017, 
                       "younger.17", "older.17"), 
                levels = c("younger.17", "older.17"))
pander(table("17학번 기준" = ID.17, "그룹" = class_roll$group))
ID.16 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2016, 
                       "younger.16", "older.16"), 
                levels = c("younger.16", "older.16"))
pander(table("16학번 기준" = ID.16, 
             "그룹" = class_roll$group))
# table("16학번 기준" = ID.16, 
#             "그룹" = class_roll$group)
ID.15 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2015, 
                       "younger.15", "older.15"), 
                levels = c("younger.15", "older.15"))
pander(table("15학번 기준" = ID.15, 
             "그룹" = class_roll$group))
ID.14 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2014, 
                       "younger.14", "older.14"), 
                levels = c("younger.14", "older.14"))
pander(table("14학번 기준" = ID.14, 
             "그룹" = class_roll$group))
ID.13 <- factor(ifelse(substr(class_roll$id, 1, 4) >= 2013, 
                       "younger.13", "older.13"), 
                levels = c("younger.13", "older.13"))
pander(table("13학번 기준" = ID.13, 
             "그룹" = class_roll$group))
```

### 학번 홀짝

```{r, odd or even, echo = FALSE}
odd.even <- as.numeric(class_roll$id) %% 2
pander(table("odd_even" = odd.even, 
             "Group"= class_roll$group))
```

### e-mail 서비스업체

```{r, e_mail, echo = FALSE}
e.mail.list <- strsplit(class_roll$e.mail, "@", 
                        fixed = TRUE)
mail.com <- mapply(`[`, e.mail.list, 2)
pander(table("e-mail" = mail.com, 
             "그룹" = class_roll$group))
```

### 성씨 분포

```{r, name, echo = FALSE}
f.name <- substring(class_roll$name, 
                    first = 1, 
                    last = 1)
pander(table("Family Name" = f.name, 
             "Group" = class_roll$group))
```

### 많이 나오는 성씨

```{r, frequent names, echo = FALSE}
f.name.f <- factor(ifelse(f.name %in% c("김", "이", "박"), 
                          f.name, "기타"), 
                   levels = c("김", "이", "박", "기타"))
pander(table("Group" = class_roll$group, 
             "Family Name" = f.name.f))
```

### 학과

```{r, departments, echo = FALSE}
# pander(class_roll)
pander(table("그룹" = class_roll$group, 
             "학과" = class_roll$dept))
```

<!--
### 전체 출석부

```{r, colleges}
# pander(class_roll)
class_roll.order <- class_roll[order(class_roll$name), ]
pander(class_roll.order)
nrow(class_roll.order)
class_roll.group <- class_roll[order(class_roll$group, class_roll$name), ]
pander(class_roll.group)
# write.csv(class_roll.group, 
#           file = "../data/class_roll_group.csv", 
#          row.names = FALSE)
#>write.csv 나 write_csv 로는 한글 인코딩이 깨져서 나오게 됨. 
write_excel_csv(class_roll.group,
          "../data/class_roll_group2.csv")
#table("단과대학" = class_roll$college, "그룹" = class_roll$group)
```

<P style="page-break-before:always">

```{r, list, echo = FALSE}
gr.id.o <- order(class_roll$group, class_roll$name)
id.by.gr <- class_roll[gr.id.o, c("group", "id", "name")]
red.names <- id.by.gr[id.by.gr$group=="Red", c("id", "name")]
names(red.names) <- c("학번", "이름")
# pander(red.names)
black.names <- id.by.gr[id.by.gr$group=="Black", c("id", "name")]
names(black.names) <- c("학번", "이름")
# pander(black.names)
# class_roll[red.id, "id"]
# class_roll[black.id, "id"]
# cbind(class_roll[red.id, "id"], class_roll[black.id, "id"])
# red.black.df <- data.frame("Red" = red.names, "Black" = black.names, row.names = NULL)
# red.black.ls <- list("Red" = red.names, "Black" = black.names)
# names(red.black.df) <- c("Red", "Black")
# pander(red.black.ls)
#pander(red.black.df, align = c("c", "c", "c", "c"))
```

```{r, red.names, echo = FALSE}
pander(red.names, caption = "Red")
```

<P style="page-break-before:always">

```{r, black.names, echo = FALSE}
pander(black.names, caption = "Black")
```
-->

<!--
```{r, save}
saveRDS(class_roll.order, file = "./class_roll.RDs")
save.image("../R/red_and_black_180907_data.RData")
```
-->